cmake_minimum_required(VERSION 3.6)

if(ANDROID)	    
	set(PATCH_USER_CONFIG ${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost_user_config.hpp)
else()
	set(PATCH_USER_CONFIG ${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src/boost/config/user.hpp)
endif(ANDROID)

ExternalProject_Add(external_boost
    PREFIX ${EXTERNAL_LIBRARIES_BUILD_PATH}
    URL "${boost_URL}"
    UPDATE_COMMAND ""
    DOWNLOAD_DIR "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src"
    SOURCE_DIR "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src"
    PATCH_COMMAND ${CMAKE_COMMAND} -E copy "${EXTERNAL_LIBRARIES_SOURCE_PATH}/CMakeLists.EDK.Boost.txt" "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src/CMakeLists.txt"	
	COMMAND ${CMAKE_COMMAND} -E copy "${PATCH_USER_CONFIG}" "${EXTERNAL_LIBRARIES_SOURCE_PATH}/boost/src/boost/config/user.hpp"
    CMAKE_ARGS ${COMMON_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD} -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DINSTALL_DESTINATION=include/boost -DCMAKE_PREFIX_PATH=${EXTERNAL_LIBRARIES_INSTALL_PATH} -DCMAKE_INSTALL_PREFIX=${EXTERNAL_LIBRARIES_INSTALL_PATH}
    )

add_library(boost INTERFACE)
target_include_directories(boost INTERFACE ${EXTERNAL_LIBRARIES_INSTALL_PATH}/include)
add_dependencies(boost external_boost)
